import type { FeaturedProduct, MarketplaceLink } from "./types";

/** Phase 1 featured stickers — product mockups in apps/marketing/public/products/ */
export const featuredProducts: FeaturedProduct[] = [
  {
    id: "lady-of-the-scales",
    baseSku: "E7-LADYSCALES",
    name: "Lady of the Scales",
    character: "Lady of the Scales",
    franchise: "Epic Seven",
    accent: "#7ec8ff",
    image: "/products/lady-of-the-scales.png",
  },
  {
    id: "makima",
    baseSku: "CSM-MAKIMA",
    name: "Makima",
    character: "Makima",
    franchise: "Chainsaw Man",
    accent: "#ff6b8a",
    image: "/products/makima.png",
  },
  {
    id: "nami-robin",
    baseSku: "OP-NAMIROBIN",
    name: "Nami & Robin",
    character: "Nami & Robin",
    franchise: "One Piece",
    accent: "#ff8c42",
    image: "/products/nami-robin.png",
  },
  {
    id: "rhianna-luciella",
    baseSku: "E7-RHIANNALUCIELLA",
    name: "Rhianna & Luciella",
    character: "Rhianna & Luciella",
    franchise: "Epic Seven",
    accent: "#c9a0ff",
    image: "/products/rhianna-luciella.png",
  },
  {
    id: "setsuka",
    baseSku: "E7-SETSUKA",
    name: "Setsuka",
    character: "Setsuka",
    franchise: "Epic Seven",
    accent: "#e85d75",
    image: "/products/setsuka.png",
  },
  {
    id: "tamamo",
    baseSku: "FGO-TAMAMO",
    name: "Tamamo no Mae",
    character: "Tamamo no Mae",
    franchise: "Fate/Grand Order",
    accent: "#ffb6cc",
    image: "/products/tamamo.png",
  },
  {
    id: "nurse-aria",
    baseSku: "E7-NURSEARIA",
    name: "Nurse Aria",
    character: "Nurse Aria",
    franchise: "Epic Seven",
    accent: "#b388ff",
    image: "/products/nurse-aria.png",
  },
  {
    id: "unohana",
    baseSku: "BLEACH-UNOHANA",
    name: "Retsu Unohana",
    character: "Retsu Unohana",
    franchise: "Bleach",
    accent: "#9b7bff",
    image: "/products/unohana.png",
  },
];

export const marketplaceLinks: MarketplaceLink[] = [
  {
    id: "etsy",
    name: "Etsy",
    description: "Handcrafted listings & limited drops",
    href: "https://atelierinkstar.etsy.com",
    accent: "#f1641e",
  },
  {
    id: "tiktok",
    name: "TikTok Shop",
    description: "Live drops & trending releases",
    href: "https://shop.tiktok.com/us/store/atelierinkstar/7494648125875652077",
    accent: "#25f4ee",
  },
  {
    id: "ebay",
    name: "eBay",
    description: "Collectible finds & rare editions",
    href: "https://www.ebay.com/usr/atelierinkstarshop",
    accent: "#e53238",
  },
];
